Feature/d 10 readiness
itk-dev/hoeringsportal pull request #343
Opened 2023-08-16 12:38 UTC by martinyde

Preparing for d 10.
Still some way to go but this prepares our custom modules and updates drupal contrib modules.

- Make custom modules and themes pass code analysis and compatible with d10
- Update contrib modules (Major versions):
    - better_exposed_filters
    - captcha
    - color_field
    - openid_connect
    - search_autocomplete
    - toolbar_visibility
    - twig_tweak
    - viewsreference

2023-08-16 13:31 UTC, rimi-itk requested changes
Looks good. 

We should go for just `core_version_requirement: ^10` in custom modules to keep things clean.

2023-08-16 13:31 UTC, rimi-itk commented on web/modules/custom/hoeringsportal_data/src/Controller/Api/HearingController.php
> +    $data = $this->serializer->serialize($entity, 'json');
🎉

2023-08-17 06:51 UTC, martinyde commented on web/modules/custom/aarhus_hero/aarhus_hero.info.yml
> +core_version_requirement: ^8.8 || ^9 || ^10
I'd prefer to make the site completely ready on d9 before making the actual update to 10. The 2nd step should include the actual ^9 -> ^10 and deleting modules that was disabled in step one. I guess we could hold the info.yml changes  (^10 only) to that step as well. But for this code to work now on d9 we need it.

2023-08-17 06:53 UTC, martinyde commented on web/modules/custom/hoeringsportal_project_timeline/assets/public/build/manifest.json
I think that is for a separate issue.

2023-11-24 13:43 UTC, rimi-itk approved these changes
Approved with a comment.

2023-11-24 13:43 UTC, rimi-itk commented on web/modules/custom/hoeringsportal_base_fixtures/src/Helper/Helper.php
> +    foreach (glob($document_source_path . '/*.docx') as $document) {
This code duplicates the PDF stuff above. Consider rewriting to 

```php
$extensions = ['pdf', 'docx'];
foreach ($extensions as $extension) {
  foreach (glob($document_source_path . '/*.' . $extension) as $document) {
    $destination = $this->fileSystem->copy($document, $document_target_path . '/' . basename($document), FileSystemInterface::EXISTS_REPLACE);
    $documents[] = $destination;
  }
}
```

2024-01-24 09:03 UTC, merged